### ISSUE TITLE
Initialize source_dir in ThemeDataReader

### ISSUE THREAD

**Issue by jorgeecardona** [ashmaroli/jekyll-data#39]
Hi, 

I am sorry for the raw issue; I am not a ruby native. I was building my blog and run into problems with jekyll 4.2.0. The class data_reader has a @source_dir that needs to be initialized, in your code you inherit from that class but don't initialize the variable that is then used but is nil, so path.sub raise an error.

```console
	11: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
	10: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
	 9: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:78:in `process'
	 8: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:181:in `read'
	 7: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-data-1.1.0/lib/jekyll-data/reader.rb:18:in `read'
	 6: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-data-1.1.0/lib/jekyll-data/reader.rb:29:in `read_theme_data'
	 5: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-data-1.1.0/lib/jekyll-data/theme_data_reader.rb:17:in `read'
	 4: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-data-1.1.0/lib/jekyll-data/theme_data_reader.rb:28:in `read_data_to'
	 3: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-data-1.1.0/lib/jekyll-data/theme_data_reader.rb:28:in `each'
	 2: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-data-1.1.0/lib/jekyll-data/theme_data_reader.rb:36:in `block in read_data_to'
	 1: from /home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll/readers/data_reader.rb:61:in `read_data_file'
/home/who/blog/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.0/lib/jekyll/readers/data_reader.rb:61:in `sub': wrong argument type nil (expected Regexp) (TypeError)
```

That new variable(?) was added here (just 2 months ago): https://github.com/jekyll/jekyll/pull/8481

I hope this helps.

**Comment by ashmaroli** [comment]
I'll try to ship a new version soon. Until then, you may point your Gemfile to this GitHub repository:
```ruby
gem 'jekyll-data', github: 'ashmaroli/jekyll-data'
```

**Comment by ronaldtse** [comment]
Hi @ashmaroli , we are encountering the same issue across several sites. Would the release occur soon? Thank you for the great gem!
